version: "3.8"

services:
  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    networks: [movie-net]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app:
    image: movie-app:multi
    environment:
      - REDIS_HOST=redis
    networks: [movie-net]
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
      resources:
        limits:
          memory: 256M

networks:
  movie-net:
    driver: overlay
